# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b257cd87f152a85b5b439a3458f99e41e7f41b4f5b0470a53fd6fb8378a3282c3660cd408a2e316b2c3e8071f0514af4b9a7eefea84ed5bfa8113e193a22b2c0

test:
  secret_key_base: e017adca537dd5022ffd18fae74c2269f65a587354adc0e4f545b537a0772a81849121392ffecbc80e23d9ce8281136d3fddbff79fef24c5d60521aa22d5adbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
